#!/usr/bin/env ruby
require 'rubygems'

require 'xmpp4r'
require 'xmpp4r/muc/helper/simplemucclient'
require 'filewatch/tail'
require 'yaml'

# TODO: these go in lib/? how does one package a "program" with its supporting
# files in Ruby anyhow?
require './lib/jabberclient.rb'
require './lib/logtail.rb'

$config = YAML.load_file("./config.yml")
$muc = connect_jabber_muc()
tail_logs_forever()